use_default_settings: true

general:
  debug: false

search:
  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  secret_key: "thebestappeva-local-searxng"
